// Audio analysis pipeline — extracts visual-driving signals from raw audio state.
// Owns normalization, peak hold, beat intensity tracking, rank resolution,
// and the two-phase analysis window for mapping frequency bands to effect bindings.

use rhythm_grid::audio::{RollingEnergy, BeatConfidence};
use super::audio_output::AudioState;
use super::effects::AudioFrame;
use super::effects::themes::SignalRank;

pub struct AudioAnalysis {
    // Raw band data (copied from AudioState each frame)
    pub bands: [f32; 7],
    pub centroid: f32,
    pub flux: f32,
    pub amplitude: f32,
    pub beat_intensity: f32,
    pub bass: f32,
    pub mids: f32,
    pub highs: f32,

    // Processed signals
    pub bands_norm: [f32; 7],          // each band normalized to its own ceiling (0-1)
    pub peak_bands: [f32; 7],          // slow decay peak hold
    pub band_beat_intensity: [f32; 7], // per-band beat decay (1.0 on beat, decays)
    norm_ceil: [f32; 7],               // fast decay normalization ceiling

    // Rank resolution (which bands drive which effects)
    pub resolved_ranks: [usize; 3],    // band indices for rank 1, 2, 3
    pub ranks_locked: bool,

    // Analysis trackers
    rolling_energy: RollingEnergy,
    beat_confidence: BeatConfidence,
    pub energy_averages: [f32; 7],     // cached for debug dashboard
    pub confidence_values: [f32; 7],   // cached for debug dashboard

    // Track change detection
    pub track_time: f64,
    last_track_name: String,

    // Beat edge detection
    prev_beat: bool,
    pub got_beat: bool,                // true on the frame a new beat arrives

    // Toast messages generated by analysis phases
    pub toast: Option<(String, f32)>,  // (text, duration) — consumed by GameWorld
}

impl AudioAnalysis {
    pub fn new() -> Self {
        AudioAnalysis {
            bands: [0.0; 7],
            centroid: 0.0,
            flux: 0.0,
            amplitude: 0.0,
            beat_intensity: 0.0,
            bass: 0.0,
            mids: 0.0,
            highs: 0.0,
            bands_norm: [0.0; 7],
            peak_bands: [0.0; 7],
            band_beat_intensity: [0.0; 7],
            norm_ceil: [0.01; 7],
            resolved_ranks: [0, 1, 2],
            ranks_locked: false,
            rolling_energy: RollingEnergy::new(10.0, 60.0),
            beat_confidence: BeatConfidence::new(),
            energy_averages: [0.0; 7],
            confidence_values: [0.0; 7],
            track_time: 0.0,
            last_track_name: String::new(),
            prev_beat: false,
            got_beat: false,
            toast: None,
        }
    }

    /// Pull raw audio state and run the full analysis pipeline.
    /// Call once per frame before effects update.
    pub fn update(&mut self, audio: &mut AudioState, dt: f64) {
        audio.tick(dt as f32);

        // Detect track change — reset all analysis state
        if audio.track_name != self.last_track_name && !audio.track_name.is_empty() {
            self.last_track_name = audio.track_name.clone();
            self.track_time = 0.0;
            self.ranks_locked = false;
            self.rolling_energy = RollingEnergy::new(10.0, 60.0);
            self.beat_confidence = BeatConfidence::new();
            self.energy_averages = [0.0; 7];
            self.confidence_values = [0.0; 7];
            self.norm_ceil = [0.01; 7];
            self.peak_bands = [0.0; 7];
            self.bands_norm = [0.0; 7];
            self.band_beat_intensity = [0.0; 7];
        }

        // Copy raw values
        self.beat_intensity = audio.beat_intensity;
        self.amplitude = audio.amplitude;
        self.bass = audio.bass;
        self.mids = audio.mids;
        self.highs = audio.highs;
        self.bands = audio.bands;
        self.centroid = audio.centroid;
        self.flux = audio.flux;
        for i in 0..7 {
            if audio.band_beats[i] {
                self.band_beat_intensity[i] = 1.0;
            }
        }
        audio.band_beats = [false; 7];
        self.got_beat = audio.beat_intensity > 0.9;

        // Feed analysis trackers
        self.rolling_energy.update(&self.bands);
        self.beat_confidence.update(&[
            self.band_beat_intensity[0] > 0.95,
            self.band_beat_intensity[1] > 0.95,
            self.band_beat_intensity[2] > 0.95,
            self.band_beat_intensity[3] > 0.95,
            self.band_beat_intensity[4] > 0.95,
            self.band_beat_intensity[5] > 0.95,
            self.band_beat_intensity[6] > 0.95,
        ], self.track_time);
        self.energy_averages = self.rolling_energy.averages();
        self.confidence_values = self.beat_confidence.confidence();

        // Track time + two-phase rank resolution
        self.track_time += dt;
        self.toast = None;
        let band_names = ["SUB", "BASS", "LMID", "MID", "UMID", "PRES", "BRIL"];

        // Phase labels
        if self.track_time < 7.0 {
            self.toast = Some((format!("SAMPLING {:.0}S", 7.0 - self.track_time), 2.0));
        } else if self.track_time >= 30.0 && self.track_time < 45.0 {
            self.toast = Some((format!("RESAMPLING {:.0}S", 45.0 - self.track_time), 2.0));
        }

        // Phase 1: first lock at 7s
        if !self.ranks_locked && self.track_time > 7.0 {
            self.resolved_ranks = self.resolve_ranks();
            self.ranks_locked = true;
            let [r1, r2, r3] = self.resolved_ranks;
            self.toast = Some((format!("MAPPED: {} {} {}",
                band_names[r1], band_names[r2], band_names[r3]), 3.0));
        }

        // Phase 2: reapply at 45s after 15s of fresh sampling
        if self.track_time > 45.0 && self.track_time - dt <= 45.0 {
            let new_ranks = self.resolve_ranks();
            if new_ranks != self.resolved_ranks {
                self.resolved_ranks = new_ranks;
                let [r1, r2, r3] = self.resolved_ranks;
                self.toast = Some((format!("REMAPPED: {} {} {}",
                    band_names[r1], band_names[r2], band_names[r3]), 3.0));
            }
        }

        // Peak hold (slow decay)
        let peak_decay = dt as f32 * 0.4;
        let ceil_decay = dt as f32 * 0.05;
        for i in 0..7 {
            self.peak_bands[i] = if self.bands[i] > self.peak_bands[i] {
                self.bands[i]
            } else {
                (self.peak_bands[i] - peak_decay).max(self.bands[i])
            };
            if self.bands[i] > self.norm_ceil[i] {
                self.norm_ceil[i] = self.bands[i];
            } else {
                self.norm_ceil[i] = (self.norm_ceil[i] - ceil_decay).max(0.01);
            }
            self.bands_norm[i] = (self.bands[i] / self.norm_ceil[i]).min(1.0);
        }
    }

    /// Decay beat intensities. Call AFTER effects have consumed the frame.
    pub fn decay_beats(&mut self, dt: f32) {
        for i in 0..7 {
            self.band_beat_intensity[i] = (self.band_beat_intensity[i] - dt * 8.0).max(0.0);
        }
        self.prev_beat = self.got_beat;
    }

    /// Build an AudioFrame snapshot for effect consumption.
    pub fn audio_frame(&self, danger: f32, dt: f32) -> AudioFrame {
        AudioFrame {
            bands: self.bands,
            bands_norm: self.bands_norm,
            peak_bands: self.peak_bands,
            band_beats: self.band_beat_intensity,
            centroid: self.centroid,
            flux: self.flux,
            danger,
            dt,
        }
    }

    /// Resolve a SignalRank to a concrete band index.
    pub fn resolve_rank(&self, rank: SignalRank) -> usize {
        match rank {
            SignalRank::First => self.resolved_ranks[0],
            SignalRank::Second => self.resolved_ranks[1],
            SignalRank::Third => self.resolved_ranks[2],
            SignalRank::Fixed(band) => band.min(6),
        }
    }

    /// Internal: compute rank resolution from current analysis state.
    fn resolve_ranks(&self) -> [usize; 3] {
        let dominant = self.rolling_energy.dominant_bands(3);
        let confidence = self.beat_confidence.confidence();
        let rank1 = *dominant.iter()
            .max_by(|&&a, &&b| confidence[a].partial_cmp(&confidence[b]).unwrap())
            .unwrap_or(&0);
        let others: Vec<usize> = dominant.iter().filter(|&&b| b != rank1).copied().collect();
        let rank2 = others.first().copied().unwrap_or(1);
        let rank3 = others.get(1).copied().unwrap_or(2);
        [rank1, rank2, rank3]
    }

    /// Whether track change just happened (for external reset logic like firework cooldown)
    pub fn track_changed(&self) -> bool {
        self.track_time < 0.1
    }
}
